name: GTFS Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Create validate directory
      run: mkdir -p validate/

    - name: Run GTFS Validator
      run: docker run --rm -v ./:/work ghcr.io/mobilitydata/gtfs-validator:latest -c in -i /work/data/ -o /work/validate/

    - name: Upload validation report
      uses: actions/upload-artifact@v5
      with:
        name: gtfs-validation-report
        path: validate/report.html